config/routes.rb
Googlemap::Application.routes.draw do
  devise_for :admins
  
  root :to => 'places#index'
  
  namespace :admins do
    root :to => 'places#index'
  end
  
  resources :places do
    collection do
      get 'search'
    end
    
    member do
      get 'approve'
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/place.rb
class Place < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  validates :latitude, :presence => true, :numericality => true
  validates :longitude, :presence => true, :numericality => true
  
  #before_create :set_status
  
  scope :approved, where(["status = ?", 'approved'])
  scope :suggested, where(["status = ?", 'suggested'])
  
  #def set_status
  # self.status = admin_signed_in? ? 'approved' : 'suggested'
  #end
end

app/controllers/admins_controller.rb
class Admins::SessionsController < Device::RegistrationsController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_filter :get_places
  before_filter :authenticate_admin!, :except => [:index, :new, :create, :search]
  
  def index
    @place = Place.new
    
    respond_to do |format|
      format.html
      format.js
     end
  end
  
  def new
    @place = Place.new
    
    respond_to do |format|
      format.html
    end
  end
  
  def edit
    @place = Place.find params[:id]
  end
  
  def create
    @place = Place.new params[:place]
    set_status
    get_places
    
    @place.save
    respond_to do |format|
      format.js
    end
  end
  
  def update
    @place = Place.find(params[:id])
    set_status

    respond_to do |format|
      if @place.update_attributes(params[:place])
        #format.html { redirect_to places_path }
        format.js
      else
        #format.html { render :action => "edit" }
        format.js
      end
    end
  end
  
  def destroy
    @place = Place.find params[:id]
    @place.destroy
    
    respond_to do |format|
      format.js
    end
    
  end

  def search
    @place = Place.find_by_name(params[:location_name])  
  end

  def approve
    @place = Place.find(params[:id])
    set_status
    @place.update_attributes params[:place]
  end

  private
  
  def get_places
    @places = Place.approved
    @suggested = Place.suggested
  end
  
  def set_status
    @place.status = admin_signed_in? ? 'approved' : 'suggested'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Googlemap</title>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "http://maps.google.com/maps/api/js?sensor=true", "https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js", 'application', 'rails' %>
  </head>
  <body>
  <div class="container_12">
  <%= yield %>
  </div>
  </body>
</html>

app/views/places/_approvedlist.html.erb
<% if @places == []%>

  There are no locations yet.
  
<% else %>
  
<table id="approved-table"> 
    <% @places.each do |place| %>
  <tr class="<%= cycle("odd", "")%>">
    <td><%= place.name %></td>
    <td><%= link_to 'edit', edit_place_path(place), :remote => true%></td>
    <td><%= link_to 'delete', place, :confirm => "Are you sure you want to delete #{place.name}?", :method => :delete, :remote => true %></td>
  </tr>
  
    <% end %>
  
</table>  

<% end %>

app/views/places/_editform.html.erb
<%= form_for @place, :url => { :action => :update}, :remote => true do |p| %>
    <%= render :partial => 'form',  :locals => { :p => p } %>
 <% end %>

 <%= link_to 'Back to confirmed places', places_path, :remote => true %> 

app/views/places/_form.html.erb
 <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this author from being added:</h2>

      <ol>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ol>
    </div>
  <% end %>
  <%= flash[:error] if flash[:error] %>
  <div class="field">
    <%= p.label :name %><br />
    <%= p.text_field :name%>
  </div>
  <div class="field">
    <%= p.label :latitude %><br />
    <%= p.text_field :latitude%>
  </div>
  <div class="field">
    <%= p.label :longitude %><br />
    <%= p.text_field :longitude%>
  </div>
  
  <div class="actions">
    <%= p.submit %>
  </div>

app/views/places/_map.html.erb
<div class="grid_5">
    <div id="map_canvas" style="width: 500px; height: 500px; margin: auto;"></div>
</div>

app/views/places/_suggestedlist.html.erb
  <% if @suggested == []%>

  There are no suggested locations.
  
  <% else %>

<table> 
    <% @suggested.each do |place| %>
  <tr class="<%= cycle("odd", "")%>">
    <td><%= place.name %></td>
    
    <td><%= link_to 'approve', approve_place_path(place), :remote => :true %></td>
    <td><%= link_to 'delete', place, :confirm => 'Are you sure?', :method => :delete%></td>
  </tr>
  
    <% end %>
    
</table>  

  <% end %>

app/views/places/approve.js.erb
alert("<%= @place.name %> approved.");
$('#approved-list').html("<%= escape_javascript render 'approvedlist'%>");
$('#suggested-list').html("<%= escape_javascript render 'suggestedlist'%>")

app/views/places/create.js.erb
$('#flash').html('')

$('#flash').html('<% flash[:notice] %>')

var locations = []
<% @places.each do |place|  %> 
   locations.push('<%= place.name %>') 
<% end %>

<script type="text/javascript">
(function($) {
  $('#search-button').click(function(){
    var location = $('#location').val();
    <% p = Place.find_by_name('%> location <%') %>
    <%if p != nil%>
        initialize(<%= p.latitude %>,<%= p.lo%>)
    <% end %>
  });

}(jQuery);
 
</script>
<div id="input">

app/views/places/destroy.js.erb
$('#approved-list').html("<%= escape_javascript render 'approvedlist'%>");

app/views/places/edit.html.erb
<h1>Edit <% @place.name %></h1>

<%= form_for @place, :url => { :action => :update} do |p| %>
<%= render :partial => 'form',  :locals => { :p => p } %>
<% end %>

app/views/places/edit.js.erb
initialize(<%= @place.latitude%>, <%= @place.longitude%>);

$('#place_latitude').attr('id', 'add_lat');
$('#place_longitude').attr('id', 'add_long');
$('#approved-list').prev().html('Edit Place');
$('#approved-list').html('<%= escape_javascript render 'editform' %>');

app/views/places/edit_backup.html.erb
<script type="text/javascript">
  lat = <%= @place.latitude %>; 
  lng = <%= @place.longitude %>;
</script>
<div class="grid_3">
  <h1>Edit <% @place.name %></h1>

  <%= form_for @place, :url => { :action => :update} do |p| %>
    <%= render :partial => 'form',  :locals => { :p => p } %>
  <% end %>
<%= link_to 'Back', places_path%>  
</div>

<%= render :partial => 'map' %>

app/views/places/index.html.erb
<div class="grid_3">
  <h2>Search Location</h2>
  <%= form_tag(search_places_path, :remote => true, :method => :get) do%>
    <%= text_field_tag 'location_name' %>
    <%= submit_tag 'Search' %>
  <% end %>

  <% title = admin_signed_in? ? "add new place" : "suggest a place" %>
  <a href="#" id="add-suggest-button"><%= title %></a>

  <div id="add-suggest-form">
  <%= form_for @place, :url => { :action => :create }, :remote => true do |p| %>
    <%= render :partial => 'form',  :locals => { :p => p } %>
  <% end %>
  </div>

  <div id="user_nav">
  
  <% if not admin_signed_in? %>
  <a href="#" id="sign-in-button">Admin Sign In</a> 

  <div id="sign-in-form"> 
  <%= form_for("admin", :url => admin_session_path) do |f| %>
  <%= f.label :email %><br/>
  <%= f.text_field :email %><br/>
  <%= f.label :password %><br/>
  <%= f.password_field :password %><br/>
  <%= f.check_box :remember_me %>
  <%= f.label :remember_me %><br/>
  <%= f.submit 'Sign in' %><br/>
  <%= link_to "Forgot your password?", new_password_path('admin') %>
  </div>
<% end %>
  
  <% else %>
    Signed in as <%= current_admin.email %>.<br/> Not you?
    <%= link_to "Sign out", destroy_admin_session_path %>
  <% end %>
  
  </div>
  
</div>

<%= render :partial => 'map' %>

<div class="grid_3 prefix_0">
  
<% if admin_signed_in? %>

<h1>Admin</h1>
<h3>Confirmed Places</h3>
 
<div class="places-list" id="approved-list">
<%= render :partial => 'approvedlist' %>
</div>


<h3>Suggested Places</h3>
<div class="places-list" id="suggested-list">
<%= render :partial => 'suggestedlist' %>
</div>
<% else %>
<h3>Confirmed Places</h3>
<table id="approved-table"> 
    <% @places.each do |place| %>
  <tr class="<%= cycle("odd", "")%>">
    <td><%= place.name %></td>
  </tr>
  
    <% end %>
  
</table> 
<% end %>

</end>

app/views/places/search.js.erb
<%if @place != nil %>
 <% if @place.status == 'approved'%>
  initialize(<%= @place.latitude%>, <%= @place.longitude%>);
 <% else%>
  alert('Location of that place has been suggested but not yet approved.');
 <% end %>
<% else %>
  alert('Location not found.');
<% end %>

app/views/places/update.js.erb
<% if @place.errors.any? %>
var error_msg = "Error:\n\n";

<% @place.errors.full_messages.each do |msg| %>
  error_msg += " - <%= msg %>\n" ;  
<% end %>

alert(error_msg);

<% else %>


alert('Updated <%= @place.name %>');


$('#approved-list').html("<%= escape_javascript render 'approvedlist'%>");

$('#add_lat').attr('id', 'place_latitude');
$('#add_long').attr('id', 'place_longitude');
$('#approved-list').prev().html('Confirmed Places');
<% end %>